# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('opt_out', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.CharField(max_length=3)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fund_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('camp_name', models.CharField(max_length=255)),
                ('tick_price1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tick_price3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tick_price10', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_id', models.CharField(max_length=8)),
                ('sale_date', models.DateField(blank=True)),
                ('tick_type', models.SmallIntegerField(blank=True)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Buyer')),
                ('camp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Campaign')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Seller')),
            ],
        ),
    ]
